---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-stream-stack-tanx-v1-storeset
  failurePolicy: Fail
  name: mstoreset.kb.io
  rules:
  - apiGroups:
    - core.stream-stack.tanx
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - storesets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-stream-stack-tanx-v1-storeset
  failurePolicy: Fail
  name: vstoreset.kb.io
  rules:
  - apiGroups:
    - core.stream-stack.tanx
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - storesets
  sideEffects: None
