---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.stream-stack.tanx
  resources:
  - storesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.stream-stack.tanx
  resources:
  - storesets/finalizers
  verbs:
  - update
- apiGroups:
  - core.stream-stack.tanx
  resources:
  - storesets/status
  verbs:
  - get
  - patch
  - update
