# permissions for end users to view storesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storeset-viewer-role
rules:
- apiGroups:
  - core.stream-stack.tanx
  resources:
  - storesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.stream-stack.tanx
  resources:
  - storesets/status
  verbs:
  - get
