# permissions for end users to edit storesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storeset-editor-role
rules:
- apiGroups:
  - core.stream-stack.tanx
  resources:
  - storesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.stream-stack.tanx
  resources:
  - storesets/status
  verbs:
  - get
