# permissions for end users to edit subscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscription-editor-role
rules:
- apiGroups:
  - knative.stream-stack.tanx
  resources:
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - knative.stream-stack.tanx
  resources:
  - subscriptions/status
  verbs:
  - get
