apiVersion: knative.stream-stack.tanx/v1
kind: Broker
metadata:
  name: test
  namespace: default
spec:
#  selector:
#    matchLabels:
  partition:
    counter:
      count: 1000
  dispatcher:
    replicas: 1
    image: ccr.ccs.tencentyun.com/stream/dispatcher:latest
  publisher:
    replicas: 1
    image: ccr.ccs.tencentyun.com/stream/publisher:latest
