apiVersion: knative.stream-stack.tanx/v1
kind: Subscription
metadata:
  name: test-svc
spec:
  broker: test
  subscriber:
    service:
      name: hello-display
      namespace: default
      port: 80
      path: /
---
apiVersion: knative.stream-stack.tanx/v1
kind: Subscription
metadata:
  name: test-uri
spec:
  broker: test
  subscriber:
    uri:
      uri: www.baidu.com
      protocol: http