//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerDefault) DeepCopyInto(out *BrokerDefault) {
	*out = *in
	out.Dispatcher = in.Dispatcher
	out.Publisher = in.Publisher
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerDefault.
func (in *BrokerDefault) DeepCopy() *BrokerDefault {
	if in == nil {
		return nil
	}
	out := new(BrokerDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatcherDefault) DeepCopyInto(out *DispatcherDefault) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatcherDefault.
func (in *DispatcherDefault) DeepCopy() *DispatcherDefault {
	if in == nil {
		return nil
	}
	out := new(DispatcherDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublisherDefault) DeepCopyInto(out *PublisherDefault) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublisherDefault.
func (in *PublisherDefault) DeepCopy() *PublisherDefault {
	if in == nil {
		return nil
	}
	out := new(PublisherDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreDefault) DeepCopyInto(out *StoreDefault) {
	*out = *in
	out.GrpcTimeOut = in.GrpcTimeOut
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreDefault.
func (in *StoreDefault) DeepCopy() *StoreDefault {
	if in == nil {
		return nil
	}
	out := new(StoreDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamControllerConfig) DeepCopyInto(out *StreamControllerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ControllerManagerConfigurationSpec.DeepCopyInto(&out.ControllerManagerConfigurationSpec)
	out.Workflow = in.Workflow
	out.Subscription = in.Subscription
	out.Store = in.Store
	out.Broker = in.Broker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamControllerConfig.
func (in *StreamControllerConfig) DeepCopy() *StreamControllerConfig {
	if in == nil {
		return nil
	}
	out := new(StreamControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StreamControllerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionDefault) DeepCopyInto(out *SubscriptionDefault) {
	*out = *in
	out.MaxRequestDuration = in.MaxRequestDuration
	out.AckDuration = in.AckDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionDefault.
func (in *SubscriptionDefault) DeepCopy() *SubscriptionDefault {
	if in == nil {
		return nil
	}
	out := new(SubscriptionDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowDefault) DeepCopyInto(out *WorkflowDefault) {
	*out = *in
	out.RetryDuration = in.RetryDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowDefault.
func (in *WorkflowDefault) DeepCopy() *WorkflowDefault {
	if in == nil {
		return nil
	}
	out := new(WorkflowDefault)
	in.DeepCopyInto(out)
	return out
}
