apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .ObjectMeta.Name -}}-dispatcher
  namespace: {{ .ObjectMeta.Namespace -}}
  labels:
    module: dispatcher
{{range $key,$value := .ObjectMeta.Labels}}
    {{$key}}: {{$value -}}
{{end}}
spec:
  serviceName: {{ .ObjectMeta.Name -}}-dispatcher
  replicas: {{ .Spec.Dispatcher.Replicas}}
  selector:
    matchLabels:
      module: dispatcher
{{range $key,$value := .ObjectMeta.Labels}}
      {{$key}}: {{$value -}}
{{end}}
  template:
    metadata:
      labels:
        module: dispatcher
{{range $key,$value := .ObjectMeta.Labels}}
        {{$key}}: {{$value -}}
{{end}}
    spec:
      containers:
        - name: dispatcher
          image: {{ .Spec.Dispatcher.Image -}}
          ports:
            - containerPort: 80
              name: http-cloudevent
            - containerPort: 8088
              name: grpc-manager
          command:
            - './dispatcher'
          workingDir: '/'
          args:
            - '--Address='