apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ GetDispatcherDeptName .}}
  namespace: {{ .ObjectMeta.Namespace }}
  labels:
    module: dispatcher
    broker: {{ .ObjectMeta.Name -}}
{{range $key,$value := .ObjectMeta.Labels}}
    {{$key}}: {{$value -}}
{{end}}
spec:
  replicas: {{ .Spec.Dispatcher.Replicas}}
  selector:
    matchLabels:
      module: dispatcher
      broker: {{ .ObjectMeta.Name -}}
{{range $key,$value := .ObjectMeta.Labels}}
      {{$key}}: {{$value -}}
{{end}}
  template:
    metadata:
      labels:
        module: dispatcher
        broker: {{ .ObjectMeta.Name -}}
{{range $key,$value := .ObjectMeta.Labels}}
        {{$key}}: {{$value -}}
{{end}}
    spec:
      serviceAccountName: {{ .ObjectMeta.Name }}
      containers:
        - name: dispatcher
          image: {{ .Spec.Dispatcher.Image }}
          ports:
            - containerPort: 80
              name: http-cloudevent
          livenessProbe:
            httpGet:
              path: /health
              port: {{ GetDispatcherManagerContainerPort }}
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ GetDispatcherManagerContainerPort }}
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          command:
            - './dispatcher'
          workingDir: '/'
          args:
            - '--STREAM_NAME={{GetStreamName . }} --SELECTOR={{GetSelector . }}'