apiVersion: v1
kind: Service
metadata:
  name: {{ .ObjectMeta.Name -}}-dispatcher
  namespace: {{ .ObjectMeta.Namespace -}}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http-cloudevent
    - port: 8088
      protocol: TCP
      targetPort: 8088
      name: grpc-manager
  selector:
    module: dispatcher
{{range $key,$value := .ObjectMeta.Labels}}
    {{$key}}: {{$value -}}
{{end}}