apiVersion: v1
kind: Service
metadata:
  name: {{ GetDispatcherDeptName .}}
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http-cloudevent
  selector:
    module: dispatcher
    broker: {{ .ObjectMeta.Name -}}
{{range $key,$value := .ObjectMeta.Labels}}
    {{$key}}: {{$value -}}
{{end}}