apiVersion: v1
kind: Service
metadata:
  name: {{ GetPublisherStsName .}}
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  ports:
    - port: {{ GetPublisherContainerPort }}
      protocol: TCP
      targetPort: {{ GetPublisherContainerPort }}
      name: grpc-manager
  selector:
    module: publisher
    broker: {{ .ObjectMeta.Name }}
{{range $key,$value := .ObjectMeta.Labels}}
    {{$key}}: {{$value -}}
{{end}}