apiVersion: v1
kind: Service
metadata:
  name: {{ .ObjectMeta.Name -}}-publisher
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
      name: grpc-manager
  selector:
    module: publisher
    broker: {{ .ObjectMeta.Name }}
{{range $key,$value := .ObjectMeta.Labels}}
    {{$key}}: {{$value -}}
{{end}}