apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ GetPublisherStsName .}}
  namespace: {{ .ObjectMeta.Namespace }}
  labels:
    module: publisher
    broker: {{ .ObjectMeta.Name }}
{{range $key,$value := .ObjectMeta.Labels}}
    {{$key}}: {{$value -}}
{{end}}
spec:
  serviceName: {{ GetPublisherStsName .}}
  replicas: {{ .Spec.Publisher.Replicas}}
  selector:
    matchLabels:
      module: publisher
      broker: {{ .ObjectMeta.Name }}
{{range $key,$value := .ObjectMeta.Labels}}
      {{$key}}: {{$value -}}
{{end}}
  template:
    metadata:
      labels:
        module: publisher
        broker: {{ .ObjectMeta.Name }}
{{range $key,$value := .ObjectMeta.Labels}}
        {{$key}}: {{$value -}}
{{end}}
    spec:
      containers:
        - name: publisher
          image: {{ .Spec.Publisher.Image }}
          ports:
            - containerPort: {{ GetPublisherContainerPort }}
              name: grpc-manager
          livenessProbe:
            httpGet:
              path: /health
              port: {{ GetPublisherContainerPort }}
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ GetPublisherContainerPort }}
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
#          command:
#            - './publisher'
#          workingDir: '/'
#          args:
#            - '--Address='